=== jjok/Decomposer/resource/schema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema elementFormDefault="qualified"
		   xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="decomposer">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="keep" minOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="path" type="xs:string" minOccurs="1" maxOccurs="unbounded" />
						</xs:sequence>
						<xs:attribute type="xs:string" name="start"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== jjok/Decomposer/tests/dummies/dummy2.xml
<?xml version="1.0" encoding="UTF-8"?>
<decomposer xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			xsi:noNamespaceSchemaLocation="resource/schema.xsd">
	<keep start="some-start-path">
		<path>test-path</path>
	</keep>
	<keep start="some-start-path2">
		<path>test-path</path>
		<path>another-test-path</path>
	</keep>
	<keep start="some-start-path3">
		<path>test-path</path>
		<path>another-test-path</path>
		<path>another-test-path2</path>
		<path>another-test-path3</path>
	</keep>
</decomposer>

=== jjok/Decomposer/decomposer.dist.xml
<?xml version="1.0" encoding="UTF-8"?>
<decomposer xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			xsi:noNamespaceSchemaLocation="https://raw.github.com/jjok/Decomposer/master/resource/schema.xsd">
	<keep start="vendor">
		<path>autoload.php</path>
		<path>composer</path>
		<path>symfony/console/Symfony/Component/Console/Application.php</path>
		<path>symfony/console/Symfony/Component/Console/ConsoleEvents.php</path>
		<path>symfony/console/Symfony/Component/Console/Shell.php</path>
		<path>symfony/console/Symfony/Component/Console/Command</path>
		<path>symfony/console/Symfony/Component/Console/Descriptor</path>
		<path>symfony/console/Symfony/Component/Console/Event</path>
		<path>symfony/console/Symfony/Component/Console/Formatter</path>
		<path>symfony/console/Symfony/Component/Console/Helper</path>
		<path>symfony/console/Symfony/Component/Console/Input</path>
		<path>symfony/console/Symfony/Component/Console/Output</path>
		<path>symfony/finder/Symfony/Component/Finder/Finder.php</path>
		<path>symfony/finder/Symfony/Component/Finder/Glob.php</path>
		<path>symfony/finder/Symfony/Component/Finder/SplFileInfo.php</path>
		<path>symfony/finder/Symfony/Component/Finder/Adapter</path>
		<path>symfony/finder/Symfony/Component/Finder/Comparator</path>
		<path>symfony/finder/Symfony/Component/Finder/Exception</path>
		<path>symfony/finder/Symfony/Component/Finder/Expression</path>
		<path>symfony/finder/Symfony/Component/Finder/Iterator</path>
		<path>symfony/finder/Symfony/Component/Finder/Shell</path>
	</keep>
</decomposer>
